services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # These ${} get substituted by Docker Compose from .env
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:alpine
    environment:
      # These ${} get substituted by Docker Compose from .env
      # POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB environment variables are used by the official Postgres image to initialize the database.
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # APP_USER and APP_PASSWORD are custom environment variables picked up by init-local-db.sh script to create a db user with specific permissions.
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    volumes:
      - ./init-local-db.sh:/docker-entrypoint-initdb.d/init-local-db.sh
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
