#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create the role
    CREATE ROLE app_role;
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO app_role;
    GRANT USAGE, CREATE ON SCHEMA public TO app_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_role;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_role;

    -- Create the user and assign the role
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    GRANT app_role TO $APP_USER;
EOSQL